--CREATE DATABASE	InLock_Games_Manha

USE InLock_Games_Manha

CREATE TABLE ESTUDIOS(
	EstudioId INT IDENTITY(1,1) PRIMARY KEY
	,NomeEstudio VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE JOGOS(
	JogoId INT IDENTITY PRIMARY KEY
	,NomeJogo VARCHAR(250) UNIQUE NOT NULL
	,Descricao VARCHAR(250) NOT NULL
	,DataLancamento DATETIME  NOT NULL
	,Valor DECIMAL NOT NULL
	,EstudioId INT NOT NULL FOREIGN KEY REFERENCES ESTUDIOS(EstudioId)
);

CREATE TABLE USUARIOS(
	UsuarioId INT IDENTITY PRIMARY KEY
	,Email VARCHAR(250) NOT NULL UNIQUE
	,Senha VARCHAR(250) NOT NULL 
	,TipoUsuario VARCHAR(250) NOT NULL
);
