--CREATE DATABASE SENAI_PERSONAGENS_MANHA

--USE SENAI_PERSONAGENS_MANHA

CREATE TABLE PERSONAGENS(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
	,NOME VARCHAR (250) NOT NULL
	,LANCAMENTO VARCHAR (250) NOT NULL
);

SELECT NOME, LANCAMENTO FROM PERSONAGENS WHERE ID = ID